# Generated by Django 4.2 on 2024-11-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='body',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
